<?php

namespace DigiTickets\JwtTests;

use DigiTickets\Jwt\JwtClaims;
use DigiTickets\Jwt\JwtData;
use DigiTickets\Jwt\JwtFactory;
use DigiTickets\Jwt\JwtParser;
use DigiTickets\JwtTests\Fixtures\UnitTestJwtConfig;
use DateTime;
use DateTimeInterface;
use DateTimeZone;
use Firebase\JWT\BeforeValidException;
use Firebase\JWT\ExpiredException;
use Firebase\JWT\JWT;
use Firebase\JWT\SignatureInvalidException;
use PHPUnit\Framework\TestCase;

class JwtFactoryAndParserTest extends TestCase
{
    /**
     * @var UnitTestJwtConfig
     */
    private $jwtConfig;

    protected function setUp(): void
    {
        parent::setUp();

        $this->jwtConfig = new UnitTestJwtConfig();
    }

    protected function tearDown(): void
    {
        JWT::$timestamp = null;

        parent::tearDown();
    }

    public function testCreateAndParseJwt()
    {
        $jwt = JwtFactory::createJwt(
            $this->jwtConfig,
            new JwtData(
                [
                    // Using some public claims listed here: https://www.iana.org/assignments/jwt/jwt.xhtml#claims
                    'given_name' => 'Homer',
                    'family_name' => 'Simpson',
                ]
            )
        );
        $this->assertIsString($jwt);

        $decoded = JwtParser::parseJwt($this->jwtConfig, $jwt);
        $this->assertInstanceOf(JwtData::class, $decoded);

        $this->assertInstanceOf(DateTime::class, $decoded->getIssuedAt());
        $this->assertGreaterThan(new DateTime(), $decoded->getExpirationTime());

        $this->assertSame('Homer', $decoded->get('given_name'));
        $this->assertSame('Simpson', $decoded->get('family_name'));
    }

    public function testCreateWithoutExpiryDate()
    {
        $jwt = JwtFactory::createJwt(
            $this->jwtConfig,
            new JwtData(['given_name' => 'Homer']),
            0
        );

        $decoded = JwtParser::parseJwt($this->jwtConfig, $jwt);
        $this->assertNull($decoded->getExpirationTime());
    }

    public function testCreateWithExplicitExpiresInMinutes()
    {
        JWT::$timestamp = (new DateTime('2023-01-01 00:00:00', new DateTimeZone('UTC')))->getTimestamp();

        $jwt = JwtFactory::createJwt($this->jwtConfig, new JwtData(), 30);
        $decoded = JwtParser::parseJwt($this->jwtConfig, $jwt);

        $this->assertSame(
            '2023-01-01 00:30:00',
            $decoded->getExpirationTime()->format('Y-m-d H:i:s')
        );
    }

    public function testCreatingAndParsingExpiredTokenThrowsException()
    {
        $jwt = JwtFactory::createJwt(
            $this->jwtConfig,
            new JwtData(
                [
                    JwtClaims::EXPIRATION_TIME => (new DateTime('2000-01-01'))->getTimestamp(),
                ]
            )
        );

        $this->expectException(ExpiredException::class);
        JwtParser::parseJwt($this->jwtConfig, $jwt);
    }

    public function testParsingMalformedStringThrowsException()
    {
        $this->expectException(\UnexpectedValueException::class);
        JwtParser::parseJwt($this->jwtConfig, 'this.is.not.a.jwt');
    }

    public function testParsingString()
    {
        // Generated by https://jwt.io/#debugger-io using the key from the setUp method.
        $jwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiQW50aG9ueSJ9.cDJy3djhmTFFUaAjuL7XY_Wx1PR5rx5i8zjT9Zf9le8';

        $parsed = JwtParser::parseJwt($this->jwtConfig, $jwt);
        $this->assertSame(
            [
                'given_name' => 'Anthony',
            ],
            $parsed->getAllData()
        );
    }

    public function testParsingTokenWithWrongSignatureThrowsException()
    {
        // Generated by https://jwt.io/#debugger-io using the key from the setUp method.
        // The first character of the signature has been changed to make it invalid.
        $jwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiQW50aG9ueSJ9.dDJy3djhmTFFUaAjuL7XY_Wx1PR5rx5i8zjT9Zf9le8';

        $this->expectException(SignatureInvalidException::class);
        JwtParser::parseJwt($this->jwtConfig, $jwt);
    }

    /**
     * You probably won't need to do this in practise. But being able to create backdated JWTs is useful for testing.
     */
    public function testTokenCanBeCreatedWithCustomIssuedAt()
    {
        $jwt = JwtFactory::createJwt(
            $this->jwtConfig,
            new JwtData(
                [
                    JwtClaims::ISSUED_AT => (new DateTime('2019-01-01', new DateTimeZone('UTC')))->getTimestamp(),
                ]
            )
        );

        $decoded = JwtParser::parseJwt($this->jwtConfig, $jwt);

        $this->assertSame(
            '2019-01-01T00:00:00+00:00',
            $decoded->getIssuedAt()->format(DateTimeInterface::ATOM)
        );
    }

    public function testParserAllowsSlightFutureIssuedAt()
    {
        $issuedAt = new DateTime('+10 SECONDS', new DateTimeZone('UTC'));
        $jwt = JwtFactory::createJwt(
            $this->jwtConfig,
            new JwtData(
                [
                    JwtClaims::ISSUED_AT => $issuedAt->getTimestamp(),
                ]
            )
        );

        $decoded = JwtParser::parseJwt($this->jwtConfig, $jwt);

        $this->assertSame(
            $issuedAt->format(DateTimeInterface::ATOM),
            $decoded->getIssuedAt()->format(DateTimeInterface::ATOM)
        );
    }

    public function testParserDoesNotAllowTooFarFutureIssuedAt()
    {
        $issuedAt = new DateTime('+90 SECONDS', new DateTimeZone('UTC'));
        $jwt = JwtFactory::createJwt(
            $this->jwtConfig,
            new JwtData(
                [
                    JwtClaims::ISSUED_AT => $issuedAt->getTimestamp(),
                ]
            )
        );

        $this->expectException(BeforeValidException::class);
        JwtParser::parseJwt($this->jwtConfig, $jwt);
    }

    public function testMockedTimeControlsExpiryTimestamp()
    {
        JWT::$timestamp = (new DateTime('2023-08-22 10:00:00', new DateTimeZone('UTC')))->getTimestamp();

        $jwt = JwtFactory::createJwt($this->jwtConfig, new JwtData());
        $decoded = JwtParser::parseJwt($this->jwtConfig, $jwt);

        $this->assertSame(
            '2023-08-22 10:01:00',
            $decoded->getExpirationTime()->format('Y-m-d H:i:s')
        );
    }
}
